version: '3.8'

# localhost 실행 시 3가지 container 가 한번에 실행되도록
services:
  # redis 설정
  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: shlRedisPwd
    command: redis-server --requirepass $$REDIS_PASSWORD
    restart: always

  # mongodb 설정
  mongodb:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: greedy
      MONGO_INITDB_DATABASE: chat
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always

  # mysql 설정
  mysql:
    image: mysql
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ohgutalk
      MYSQL_USER: shl
      MYSQL_PASSWORD: greedy
    restart: always

